global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using System.Linq;
global using System.Threading.Tasks;
global using ThAmCo.Events.Models;
global using System.Net.Http;
global using Newtonsoft.Json;
global using System.Text;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using ThAmCo.Events.DTO;
global using System.ComponentModel.DataAnnotations;
global using ThAmCo.Events.Data;
global using ThAmCo.Events.ViewModels;
global using ThAmCo.Events.IServices;
global using ThAmCo.Events.ViewModels.EventViewModels;
global using Microsoft.AspNetCore.Diagnostics;
global using ThAmCo.Events.ViewModels.CateringViewModels;
global using FoodBookingDTO = ThAmCo.Events.DTO.FoodBookingDTO;
global using FoodItemDTO = ThAmCo.Events.DTO.FoodItemDTO;
global using MenuDTO = ThAmCo.Events.DTO.MenuDTO;
global using Auth0.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Authentication;
global using Auth0.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Authentication.Cookies;
global using ThAmCo.Events.Models.Enums;